# Site settings
title: Francisco Rojas weblog
email: frojas@alumnos.utalca.cl
description: > # this means to ignore newlines until "baseurl:"
  Software Development Engineer, here you will find my different expirence
  playing with different programming methodologies, programming language,
  anything that get my attention.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://frojasg.cl" # the base hostname & protocol for your site
twitter_username: frojasg
github_username:  frojasg

# Build settings
markdown: kramdown
